source 'http://rubygems.org'

gem 'rails', '~> 3.0'
# gem 'rails', :git => 'git://github.com/rails/rails.git'
gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'tabulatr', :path => File.expand_path('../../')
gem 'id_stuffer'

group :development, :test do
  gem 'ruby-debug19'
  gem 'rspec-rails'
  gem 'capybara'
  gem 'launchy'
end